image: docker:20.10.16

stages:
  - test

test:
  stage: test
  variables:
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_DEFAULT_REGION: eu-central-1
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    LOCALSTACK_HOSTNAME: localhost.localstack.cloud
    HOSTNAME_EXTERNAL: localhost.localstack.cloud
    # Required by awscli-local to correctly resolve the endpoint
    AWS_ENDPOINT_URL: http://localhost.localstack.cloud:4566
    DYNAMODB_INIT_SCRIPTS_PATH: /builds/ShowMeYourCodeYouTube/aws-playground/localstack/dynamodb

  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false"]

  before_script:
    - cat /etc/os-release
    - apk update
    - apk add gcc musl-dev linux-headers py3-pip python3 python3-dev curl jq
    - python3 -m pip install localstack awscli awscli-local
    - python3 --version
    - pip -V
    - echo "Make sure that all files are executable."
    # If you cannot execute local files when running GitLab pipeline, for instance:
    # /bin/sh: eval: line 155: ./localstack/init-aws.sh: Permission denied
    # Instead of adding permission via Gitlab file,
    # you can commit changes with proper permissions:
    # > git add --chmod=+x ./*
    - find . -name '*.sh' -type f | xargs chmod +x
    - docker pull localstack/localstack:1.4.0
    - dind_ip="$(getent hosts docker | cut -d' ' -f1)"
    - echo "${dind_ip} localhost.localstack.cloud " >> /etc/hosts
    - DOCKER_HOST="tcp://${dind_ip}:2375" localstack start -d
    - localstack --version
    - localstack status services
    - curl -s $AWS_ENDPOINT_URL/_localstack/init | jq .
    - cd localstack && ./init-aws.sh && cd ..
  script:
    - echo "Verify project's scripts...."
